# Generated by Django 3.1.4 on 2020-12-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201203_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('booked_room_count', models.IntegerField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=50)),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.reservation')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.room')),
            ],
        ),
        migrations.CreateModel(
            name='StayRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.room')),
                ('stay_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.stay')),
            ],
        ),
    ]
