# Generated by Django 3.1.4 on 2020-12-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reservation_stay_stayroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='booked_room_count',
        ),
        migrations.RemoveField(
            model_name='stayroom',
            name='room_id',
        ),
    ]
