# Generated by Django 3.1.4 on 2020-12-04 08:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201203_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('promo_type', models.IntegerField(choices=[(1, 'Currency'), (2, 'Percentage')], default=1)),
                ('quota', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('promo_date_start', models.DateField()),
                ('promo_date_end', models.DateField()),
                ('stay_date_start', models.DateField()),
                ('stay_date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PromoRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_nights', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_rooms', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('checkin_day', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('booking_day', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('booking_hour_start', models.TimeField()),
                ('booking_hour_end', models.TimeField()),
                ('promo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.promo')),
            ],
        ),
    ]
