# Generated by Django 3.1.4 on 2020-12-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_promo_promorule'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='promo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.promo'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserve_date',
            field=models.DateField(default='2020-12-01'),
        ),
    ]
